### ISSUE TITLE
Fractal sync locking files causing .Net build issues

### ISSUE THREAD

**Issue by lawrencedine** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#105]
Not entirely sure what the right solution is here but here is the scenario:

- You start working on a site with the intention of working in C# Orchard code as well as front end JavaScript and CSS changes.
- You load up your command line and start up the theme's `npm start` command to get the pattern library, CSS and TS compilation working.
- Next you go to build the website project in Visual Studio or start debugging (triggering a build).

Depending on your luck/setup you might see a build failure in Visual Studio because `The command "npm run bundle:dev" exited with code 1.` this also sometimes manifests as an error for every single DLL in the project not being found.

I can reproduce this 100% of the time if I'm using WSL Ubuntu as my command line. I can also stop it happening by removing the `--sync` from the `start:patterns` npm script.

It seems like it's a bad interaction between the browser sync file watching of fractal and the webpack clean plugin.

**Comment by lawrencedine** [comment]
Slightly related to #38

**Comment by DannyT** [comment]
Not sure if it's any help, but I've had issues where using node on wsl conflicts with the node on windows. They aren't 100% like-for-like (unfortunately). One or the other is fine, and a clean and re-run of NPM either way works but you can't seamlessly switch between them in my experience :/
