### ISSUE TITLE
Should color settings reference the css theme default?

### ISSUE THREAD

**Issue by DannyT** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#106]
There appears to be some duplication between:

https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/master/content/Assets/Styles/settings/_color.scss

and

https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/master/content/Assets/Styles/settings/themes/_default.scss

(e.g. brandPrimary and default.color.brandPrimary)

Should one of these be referencing/overriding the other?

**Comment by bengammon** [comment]
Certainly the variables in `_default.scss` should be the single source of truth. I think these are just leftover variables, from when we switched to using a theme settings file. 

Can you open an issue and I'll take a look at it when I can. For now though, definitely make sure you're referencing `default.color.brandPrimary`

**Comment by DannyT** [comment]
@bengammon this is an issue... 😆
