### ISSUE TITLE
Add carousel component to boilerplate

### ISSUE THREAD

**Issue by bengammon** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#112]
We recently worked on a carousel component for a client and it'd be great to get the base functionality baked into the boilerplate to accompany our gallery, menu and parallax scripts

**Comment by peterkeating** [comment]
Added some of our recent carousel work to the theme and tweaked some of the HTML & CSS to improve the structure and resolve some linting issues. Be cool if @bengammon could take a look and make any design tweaks to ensure it's in a place that it looks good by default and can be easy to customise to fit any project needs.
