### ISSUE TITLE
Create template pages

### ISSUE THREAD

**Issue by bengammon** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#116]
We currently have a homepage (barebones), news landing page and article page. It'd be good to start fleshing out some pages that we know will exist across most sites we do:

- [x] About page
- [x] Games page
- [ ] Game detail page
- [ ] Contact page
- [x] Jobs page
- [ ] Job detail page

The benefit of this is that it will force us to use the available components. So if we are missing anything, this exercise will help surface that.

A future evolvement of creating these pages will be to have different layouts for these pages, based on what type of site we're creating (studio, game, event, etc).

**Comment by DannyT** [comment]
Might as well throw "People" and "Jobs" in there too

**Comment by bengammon** [comment]
I was going to include a people section on the about page and job listings on the join page? (I should have called this 'jobs page', really).

Unless you think these should be their own pages? I could include a job detail page?

**Comment by DannyT** [comment]
That sounds good 👍

**Comment by peterkeating** [comment]
Working is being done on `feature/content-pages` branch, which will be included in the next `v0.6.0` release.
