### ISSUE TITLE
Hero component should be a section modifier

### ISSUE THREAD

**Issue by bengammon** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#117]
Currently, the hero markup looks as follows:

```
<div class="hero">
    <div class="hero__content"></div>
    <div class="hero__media"></div>
</div>
```

When it should really be a section modifier:

```
<section class="section section--hero">
    <div class="section__content"></div>
    <div class="section__media"></div>
</section>
```

**Comment by peterkeating** [comment]
This change has been done within the widgets module, which defines the markup for a hero.

https://github.com/EtchUK/Etch.OrchardCore.Widgets/commit/ffb021b3a041f4c22158db99a8891674b66400f1#diff-c10d7ebf993099b41946912c6ad99cca
