### ISSUE TITLE
NullReferenceException after setup 'run'.

### ISSUE THREAD

**Issue by BJury** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#118]
I setup a test website (Microsoft.NET.Sdk.Web) with OrchardCore.Application.Cms.Targets and referenced a new theme project created using the boiler plate.

The site was setup correctly, however when I run the Setup for the boilerplate I now get an exception when browsing to the home page.

This happens in both rc1 on Nuget or using the latest dev version.
```
NullReferenceException: Object reference not set to an instance of an object.
OrchardCore.ContentManagement.Display.ContentItemDisplayManager.BuildDisplayAsync(ContentItem contentItem, IUpdateModel updater, string displayType, string groupId) in ContentDisplayManager.cs
OrchardCore.Layers.Services.LayerFilter.OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next) in LayerFilter.cs
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
OrchardCore.Diagnostics.DiagnosticsStartupFilter+<>c__DisplayClass3_0+<<Configure>b__1>d.MoveNext() in DiagnosticsStartupFilter.cs
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
OrchardCore.ContentPreview.PreviewStartupFilter+<>c+<<Configure>b__1_1>d.MoveNext() in PreviewStartupFilter.cs
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute) in ShellScope.cs
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in ModularTenantContainerMiddleware.cs
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)```

**Comment by JoeBerkley** [comment]
I've span up a new site using [our site boilerplate](https://github.com/EtchUK/Etch.OrchardCore.SiteBoilerplate) and a blank theme from this boilerplate, which I used as the setup recipe, and I'm not getting this issue.

You said on [gitter](https://gitter.im/OrchardCMS/OrchardCore?at=5e5515de1c4f1707f8cc73d4) that your admin area still works, are you able to go to the Config > Layers screen? I'm thinking the issue may be that our site boilerplate has a lot of references to our modules that the ThemeBoilerplate then creates instances of, and I'm assuming that you don't have those packages referenced

**Comment by BJury** [comment]
I made a fresh site with a fresh theme and everything was ok until I git 'Run' on the theme. Going to Layers I get the same error. I'll try the above nw.

**Comment by BJury** [comment]
Referenced those packages and the problem persists. I'll see if I can automate the creation to demonstrate.

**Comment by JoeBerkley** [comment]
It'd also be cool if you could set up an example repo that'll produce the issue once set up if you can't automate it 👍

**Comment by BJury** [comment]
I can't find them on the features list, so that does sound like it would be the cause. No idea why as the .dlls are making it to the bin directory.

For reference: https://github.com/BJury/MyOrchardWebsite

**Comment by JoeBerkley** [comment]
We got BJury set up with the boilerplate after using our SiteBoilerplate as a starting point. Another solution to the problem if the modules didnt work for you would have been to copy the migration recipe from our Widgets module, put it in the theme and run it manually from the admin area. You would then still be missing views for the items however, so you would also need to grab those from the Widgets module and put those in the theme as well.

**Comment by peterkeating** [comment]
We're going to be including the definitions described by the widgets module within the theme recipes going forward as we always customise them. The definitions created by the widgets module [no longer automatically run](https://github.com/EtchUK/Etch.OrchardCore.Widgets/commit/5c9f3492c00b4854331fcfc04c95d2859f40f391) and have to be triggered manually through the UI or code.
