### ISSUE TITLE
Setup print style sheet

### ISSUE THREAD

**Issue by peterkeating** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#127]

**Comment by Newnab** [comment]
@peterkeating This should be simple enough as it's just gonna be the HTML5BP default in order to have parity with the Umbraco version... I'm not sure where exactly it should live though. Root? As a component? Other folder? New folder altogether?

**Comment by peterkeating** [comment]
@Newnab So from here - https://github.com/h5bp/html5-boilerplate/blob/master/dist/css/main.css#L182? 

What are your thoughts on where it should live? As long as it's clear it came from h5bp, preferably through a comment. With little thought here are some options below... 

- Include it as a partial located at `vendor/h5bp/print.scss` ?
- Add `print` folder which contains a `_default.scss`
- Add `media` folder which contains `_print.scss` (

**Comment by Newnab** [comment]
I like the flexibility of option 1, which also creates a sensible place for any other vendor files to live should we need to include them in that fashion... But the downside I guess is that typically we would go on to edit this print file and add our own extras. At that point it kind of becomes not a vendor file any more...

What about:
1. Include the default as a partial located at `vendor/h6bp/_print.scss`
2. Add a folder for `vendor-overrides` and include a _print.scss in there too, for extras? The vendor overrides folder could also be where we keep things like civic cookie control overrides, as well as any other js plugin or things like Umbraco Forms on the Umbraco side, if we did it as a standard

**Comment by peterkeating** [comment]
Maybe instead of adding another directory we have.

- vendor/h5bp
     - _all.scss
     - _print.scss
     - _overrides.scss

In the main stylesheet it would load `vendor/h5bp/all`, where the `all` partial will handle everything related to h5bp.

One thing I'm not a fan of with this approach is it isn't obvious where the print styles are coming from. Potentially it should be...

- print
    - _all.scss
    - _h5bp.scss
    - _default.scss (can contain overrides or custom stuff)
