### ISSUE TITLE
Move deployment plan recipe to site boilerplate

### ISSUE THREAD

**Issue by DannyT** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#151]
As the deployment plan recipe is the same, regardless of theme, should we move this to live in the site boilerplate perhaps?

In a project which has multiple themes created from the theme boilerplate, we currently end up with multiple identical deployment plan recipes.

**Comment by peterkeating** [comment]
It would need to be in a module not the boilerplate. We could potentially only include it in our host theme as that should be used in all our projects.
