### ISSUE TITLE
Hero body alignment

### ISSUE THREAD

**Issue by bengammon** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#156]
In a recent client call, the client expressed the desire to be able to change the alignment of the `.hero__body` content via Orchard. After discussion with some of the play team, it would be cool if the modifier classes were available for changing the position to one of nine defaults (imagine a 3x3 grid):

- top left, top centre, top right
- centre left, centre (default), centre right
- bottom left, bottom centre, bottom right.

I believe the alignment of `.hero__body` should be kept separate from text alignment. For example, If the client wants `.hero__body` to be aligned against the right hand edge of the hero, they should also then be able to left align the text, if they want.

**Comment by peterkeating** [comment]
@bengammon Believe we have this now so I'm going to close the issue, feel free to re-open if you don't think we do.
