### ISSUE TITLE
Use media queries to remove unnecessary font size variables

### ISSUE THREAD

**Issue by bengammon** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#158]
We can reduce the number of font size variables that we define in the `_typography.scss` variables file, by using a media query to update the value of each variable at different breakpoints. 

For example, instead of two variables for a `H1` like this:

```
:root {
    --fontSizeH1: calc(var(--fontSizeBase) * 4);
    --fontSizeH1Mobile: calc(var(--fontSizeBase) * 2.25);
}
```

We just use one variable and update its value using a media query:

```
:root {
    --fontSizeH1: calc(var(--fontSizeBase) * 2.25);
    
    @include mq($from: tablet) {
        --fontSizeH1: calc(var(--fontSizeBase) * 4);
    }
}
```

**Comment by bengammon** [comment]
Branch: https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/tree/chore/typography-media-queries

I had a quick look at trying to implement this change but ran into an issue. Within `index.scss`, variables need to be imported first as they could be used anywhere. However, you can only use a media query if the tool for doing so, `~sass-mq`, is imported before the variables. 

Some of our tools use variables, so they have to be imported second. The only way to proceed would be to separate the `~sass-mq` tool and import it before the variables.

This is a shame because I really like the simplicity of using a media query to update the value of a variable, but `~sass-mq` is a tool, and it should be imported at the same time as the others.

Open to any thoughts or suggestions...

**Comment by peterkeating** [comment]
@bengammon As `sass-mq` is a third party tool I'd be happy for it to come out of the `tools\_all.scss` partial and specified above the `variables` import.
