### ISSUE TITLE
Change templates to use Liquid

### ISSUE THREAD

**Issue by lawrencedine** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#17]
All of the views that come with the ThemeBoilerplate can be expressed as Liquid views. Could be nice to have a template option that allows the user to choose between Liquid and Razor views.

**Comment by peterkeating** [comment]
After doing a project I think we can agree that Liquid is our preferred approach for defining templates within the theme. Let's switch the boilerplate to use Liquid instead of Razor. I don't think we need the option to use Razor to be honest.
