### ISSUE TITLE
Footer Widget feedback

### ISSUE THREAD

**Issue by DannyT** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#173]
* Move to Etch.OrchardCore.Widgets - typically a site will have a banner (header/nav) and a footer, currently the banner widget is from the Widgets package and the Footer widget is from here.
* Allow all normal widgets to be added to the Content part (e.g. Visual Editor).
* Implement our widget picker popup instead of the dropdown list or if not possible, sort the list alphabetically.

**Comment by peterkeating** [comment]
@DannyT This has been catered for by [`v0.11.0`](https://github.com/EtchUK/Etch.OrchardCore.Widgets/releases/tag/v0.11.0) of  the widgets module & [`v0.4.3`](https://github.com/EtchUK/Etch.OrchardCore.AdminTheme/releases/tag/v0.4.3) of the admin theme.
