### ISSUE TITLE
Components for Pattern Library boilerplate to always include

### ISSUE THREAD

**Issue by DannyT** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#31]
** Updated to include comment suggestions and changed to task list to show progress **

- [x] Colour palette
- [x] Font
- [x] Logo
- [x] H1-H6
- [x] Paragraph
- [x] Text formatting (bold, italic, underlined)
- [x] Hyperlinks
- [x] Image
  - [x] inline
  - [x] full-width
  - [x] left-aligned
  - [x] right-aligned
- [x] Primary button
- [x] Secondary button
- [x] Simple section
  - [x] Heading, sub-heading, image, background colour
  - [x] Left-aligned, centred, right-aligned
- [x] Unordered List
- [x] Form
  - [x] Label
  - [x] Input field
  - [ ] Guidance/intro text
- [x] Figure / figcaption
- [x] Embed (via https://embedresponsively.com/)
- [x] Blockquote
- [x] Ordered List
- [x] Card Displaying a combination of image, title & body (https://getbootstrap.com/docs/4.3/components/card/)
- [x] Media object (https://getbootstrap.com/docs/4.0/layout/media-object/)
- [x] Nav

**Comment by peterkeating** [comment]
Here are some other that I think would be good to include.

- Figure / Figcaption
- Embed (via https://embedresponsively.com/)
- Blockquote
- Ordered List (see you've got unordered, it would be good to cater for `ol` too)
- Card (Displaying a combination of image, title & body (https://getbootstrap.com/docs/4.3/components/card/)
- Media object (https://getbootstrap.com/docs/4.0/layout/media-object/)

**Comment by DannyT** [comment]
* Nav

**Comment by peterkeating** [comment]
@bengammon Can we also include "Hero", I would see this having an image with our standard breakpoints, title, blurb and CTA button.
