### ISSUE TITLE
Looks like "Widgets-ContentDefinitions" is missing?

### ISSUE THREAD

**Issue by TonyWoo** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#326]
An unhandled exception occurred while processing the request.
ArgumentException: No recipe named 'Widgets-ContentDefinitions' was found.
OrchardCore.Recipes.RecipeSteps.RecipesStep.ExecuteAsync(RecipeExecutionContext context)

**Comment by peterkeating** [comment]
@TonyWoo You need to add a reference to our widgets module - https://github.com/etchuk/etch.OrchardCore.Widgets
