### ISSUE TITLE
Anchor styles need improving

### ISSUE THREAD

**Issue by bengammon** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#42]
@JoeBerkley noticed that there are styles missing for `.link--cta-primary` and `.link--cta-secondary`. This partial is also getting pretty lengthy, so the animation classes should be moved to their own partial.

- [x] Add missing link styles
- [x] Split `_anchor.scss` into multiple partials to make them easier to manage

**Comment by Newnab** [comment]
One thing I noted during my notes during boilerplate standardisation - seems to me like `_anchor` should exist within `base` and only contain default, tag-based styles for `<a>` tags sitewide, and `_link` should be a component? Just for purity of everything in `base` being purely base stuff not based on tags.

What do you think?

**Comment by bengammon** [comment]
I totally agree. I've actually done just that here: https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/pull/81

However, I do still think it can be improved further. I read a really good article yesterday about resets that has a great technique for applying styles to `<a>` tags when they don't contain a class. I created an issue for it because there's a lot of other good stuff in there too: https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/issues/83

**Comment by peterkeating** [comment]
Closing this as seems like the work has been done and any further work is covered by #83.
