### ISSUE TITLE
Cookie Policy

### ISSUE THREAD

**Issue by peterkeating** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#44]
Every website should have a cookie policy. It would be good to have this out of the box.

**Comment by PhilDye** [comment]
A placeholder _for_ it maybe, but not the copy itself - that's legal text that a client should supply.

**Comment by peterkeating** [comment]
@PhilDye Yea definitely not the copy! We would only add the ability to add a "Cookie Policy" widget that would require a content editor to add the copy. The theme would have a sensible default display for the widget and the front-end code for dismissing the policy.

**Comment by Newnab** [comment]
Might be worth looking at third party solutions for this in terms of FE, as ICO guidance has recently evolved and got more complicated.

**Comment by peterkeating** [comment]
@Newnab Anything you have in mind?

**Comment by Newnab** [comment]
@peterkeating I don't have any actual recommendation at the minute - it's something we were considering on the Umbraco side too recently, and https://www.civicuk.com/cookie-control came up (which is what the ICO themselves use), but it has a yearly license cost for some of the features we'd probably want. I feel like there's probably an open source alternative, but it needs research to find a trusted, maintained one.

**Comment by Newnab** [comment]
Some googling turned up this as a popular open source alternative which is compliant depending on which mode you choose: https://cookieconsent.osano.com - I think this looks like a good bet but might merit further discussion

**Comment by peterkeating** [comment]
Looks like we could potentially do with a module for this as it feels like you would want to configure within the CMS how the cookie consent works. This configuration would be passed through to something like https://cookieconsent.osano.com/.

**Comment by PhilDye** [comment]
I’m not sure that alternative provides the granularity over cookie types that may be needed. This is a wider topic than just the Play boilerplate, so needs standardising across all Etch projects before a specific Play/OC implementation can be moved forward.

**Comment by peterkeating** [comment]
@PhilDye 100% agree :) For this issue I'd suggest we get the basic approach we've applied for our existing sites. We can then have the discussion of how we want to approach implementing cookie policies in a CMS before jumping in.

**Comment by Newnab** [comment]
@PhilDye As far as I understand it there's no direct need for granularity - there's just a need for opt-in on anything which isn't deemed "strictly necessary". The ICO themselves for example just have an opt in for everything non-necessary, which for them is titled "analytics" and covers a few GA ones. That same approach would serve us I think - all of our cookies are either necessary (exempt from needing consent) or are for analytics (we use more than GA, but still).

If you have any links about granularity over individual cookies being a requirement I'd be interested in reading them, because obviously that changes things!

As for BP standardisation, it's in the works! Cookie popup divergence is documented here for discussion: https://etchuk.atlassian.net/wiki/spaces/BS2/pages/964198600/Specific+JS+Components+Files and will be discussed in the near future.

**Comment by PhilDye** [comment]
@Newnab I believe granularity *is* needed; the analysis at https://blogs.dlapiper.com/privacymatters/uk-ico-publishes-significant-new-guidance-on-cookies-and-similar-technologies/ confirms 
> granularity – the ability to consent to cookies used for some purposes, but not others; and

As for purposes, the ICOs own site is indeed simple, with just Essential and Analytics - in practice, most clients will also be using social/ad tracking too at least.

**Comment by Newnab** [comment]
I see, thanks for sharing. It leaves some room for vagueness in the sense that you _could_ define your "purpose" as something very all-encompassing like "Improving your experience", but I think I agree with you is that the ICO's intent is to allow people to distinguish between e.g being analysed vs remarketed vs whatever else.

**Comment by peterkeating** [comment]
Closing as we now have https://github.com/etchuk/Etch.OrchardCore.CivicCookieControl which enables us to use [CIVIC cookie control](https://www.civicuk.com/cookie-control).
