### ISSUE TITLE
Include `textarea` default styles

### ISSUE THREAD

**Issue by peterkeating** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#47]
Add a sensible starting point for `textarea`.

**Comment by Newnab** [comment]
We actually don't seem to have default styles for any form inputs - but there is a component (form) which contains .field classes. I think this will come up in the boilerplate standardisation exercise, so might be better off waiting to agree an approach across divisions before taking too much action.

**Comment by peterkeating** [comment]
@Newnab Sounds good!

My actual preference would be to have sensible styles that target the base elements, `input`, `select`, `textarea`, etc... instead of our current `form` directory approach with `.field` class.

**Comment by bengammon** [comment]
Boilerplate standardisation would be good. Basic styling would be great, especially things like having an example of a custom checkbox.

On top of that, we should ensure that the markup for these form inputs is accessible as possible. We shouldn't have to spend time whilst on a project working out what is best for screen readers, etc. We should just be able to grab the code and go, confident that what's in the pattern library is well considered.
