### ISSUE TITLE
Add template for 404 page

### ISSUE THREAD

**Issue by peterkeating** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#49]
Add liquid template (`Views/Shared/NotFound.liquid`) that will display in the event of a 404.

**Comment by JoeBerkley** [comment]
We should also add views fro 401, 403 and 500 errors

**Comment by JoeBerkley** [comment]
Here is how other error codes are handled, it looks like anything that isn't a `404` is lumped into a general "Error" view

https://github.com/OrchardCMS/OrchardCore/blob/master/src/OrchardCore.Modules/OrchardCore.Diagnostics/Controllers/DiagnosticsController.cs

This file has been changed and merged into `dev` to include at least `403` errors, but it doesn't look like this'll be coming until RC 1.1 😞

**Comment by peterkeating** [comment]
@JoeBerkley Will play around to see if adding an `Error.liquid` template file will render out a nicer error message.
