### ISSUE TITLE
Styling Tweaks

### ISSUE THREAD

**Issue by peterkeating** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#55]
Below are a bunch of updates that need to be made to the Sass.

- [ ] Make sure all `font-size` declarations are using `@include rem` and potentially use `themify` mixin to use theme settings to drive the values
- [ ] Import `layout` before `base`
- [ ] Try to use `rem` over `px` for layout based units
- [ ] Remove `margin-bottom` on `p` when it's last-child

tbc...

**Comment by Newnab** [comment]
@peterkeating Wondering if it's worth breaking these out into separate issues? They mostly feel distinct

**Comment by peterkeating** [comment]
@Newnab Agreed!

**Comment by Newnab** [comment]
https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/issues/60
https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/issues/61
https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/issues/62
https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/issues/63
https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/issues/64
