### ISSUE TITLE
Add `hr` styles

### ISSUE THREAD

**Issue by peterkeating** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#59]
Add default styles for `hr`, specifically with the default spacing we want out the box.

**Comment by Newnab** [comment]
@bengammon What would our default hr styles be do we think? Maybe `$spacing-default` on top and bottom, and set the colour to be `$color-brand-primary`?

**Comment by peterkeating** [comment]
@Newnab I'd probably only suggest spacing be added to the bottom. Reducing the thickness that comes with a non-styled `hr` would be good also. I'll let @bengammon dictate the colour, he has the magical eye :D

**Comment by bengammon** [comment]
@Newnab With regards to colour, I think we should avoid the brand colour and use a light grey as the default. The white and black colour variables are consistent across all projects, so let's modify one of them to get our light grey:

`lighten($color-black, 80%);`

**Comment by Newnab** [comment]
@bengammon We actually seem to have a default grey already, in `$color-grey-1: #efefef;` - want me to use that or add a new one with the technique you described above?

**Comment by bengammon** [comment]
@Newnab I would prefer to use the technique I mentioned previously. Only because the grey values are highly likely to change on each project. The black and white variables will be constant.
