### ISSUE TITLE
In SCSS, import layout before base

### ISSUE THREAD

**Issue by Newnab** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#60]
In `\content\Assets\Styles\index.scss`, lines 20 and 24

**Comment by Newnab** [comment]
@peterkeating What's the reasoning behind this change?

**Comment by peterkeating** [comment]
@Newnab Noticed this was a change that we made on a client project.

> This is done so that variables in the layout partials are defined before base, components and trumps are imported
