### ISSUE TITLE
Integrate a caption in to `embed` component

### ISSUE THREAD

**Issue by peterkeating** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#68]
Can we accomodate having a caption that will be displayed beneath an embed. This will need some thought for the structure of the HTML due to the way `embed` is implemented to cater for responsive breakpoints.

The below won't work as the caption will disappear behind the `iframe` because it's using position absolute.

```
<div class="embed">
    <iframe src="..."></iframe>
    <p class="embed__caption"></p>
</div>
```

I'm thinking something along the lines of below. Happy to have alternative name for `embed__source`. Majority of styles on `embed` should be moved to `embed__source`. Definitely don't have `embed-container` followed by `embed`, really not a fan of that approach.

```
<div class="embed">
    <div class="embed__source">
        <iframe src="..."></iframe>
    </div>
    <footer class="embed__caption">This is the caption...</footer>
</div>
```

Underlying reason this is needed is because [editor.js](https://editorjs.io/) has the ability for a caption to be defined when embedding.

**Comment by bengammon** [comment]
I like the updated approach. I think `embed__source` is fine as a name (I can't think of an alternative that's more descriptive).
