### ISSUE TITLE
Form elements, styling and accessibility

### ISSUE THREAD

**Issue by bengammon** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#75]
We have some basic form styles currently included in the pattern library, but there's plenty more that we can do to expand on this:

- [x] A `Form Elements` group in the pattern library base section that includes vanilla HTML form elements
- [x] Expand upon the existing pattern library `Form` structure to show custom styling and some sensible default examples of types of forms: login, newsletter, contact us etc.
- [x] Accessibility: ensure each element is using the correct markup so that we don't need to add this when working on projects
- [x] Cater for all form elements
    - [x] Dropdown
    - [x] Radio
    - [x] Checkbox
    - [x] Text
    - [x] Textarea
    - [x] File

**Comment by bengammon** [comment]
@Newnab Has any of this ground already been covered with our Umbraco projects?

**Comment by peterkeating** [comment]
I'd like to see us tidy up `components/form` and ensure we're follow the same conventions for everything else. As @bengammon says, we should try to make sure we add styling to base elements where appropriate (`field-group` should be `fieldset`). 

Let's ensure we've gone styles/examples for different form elements (drop downs, checkboxes, radio buttons, etc...).

Would be great if this could also cover displaying validation errors as well as indicators for required fields or hint messaging to assist users with form completion.

Great thinking that this should also cover accessibility too!

**Comment by lawrencedine** [comment]
@peterkeating Regarding `field-group` and `fieldset` one complexity I found on a client project when using `fieldset` is that it doesn't support `display: flex;` (https://stackoverflow.com/questions/28078681/why-cant-fieldset-be-flex-containers) though I suppose in this case you could just nest another element to achieve that layout.

**Comment by bengammon** [comment]
@lawrencedine @peterkeating That's interesting about `fieldset` not supporting flex. I've been having a look around to see what the best practice for this is. 

Here's the typical structure that GOV.UK use:

```
<div class="form-group">
  <label class="form-label" for="full-name-f1">Full name</label>
  <input class="form-control" id="full-name-f1" type="text" name="full-name-f1">
</div>
```

When it comes to using a `fieldset`, they nest that inside the group:

```
<div class="form-group">
  <fieldset>

    <legend>
      <h1 class="heading-medium">
        How do you want to be contacted?
      </h1>
    </legend>

    <div class="multiple-choice" data-target="contact-by-email">
      <input id="example-contact-by-email" type="radio" name="radio-contact-group" value="Yes">
      <label for="example-contact-by-email">Email</label>
    </div>

    <div class="multiple-choice" data-target="contact-by-phone">
      <input id="example-contact-by-phone" type="radio" name="radio-contact-group" value="No">
      <label for="example-contact-by-phone">Phone</label>
    </div>

    <div class="multiple-choice" data-target="contact-by-text">
      <input id="example-contact-by-text" type="radio" name="radio-contact-group" value="No">
      <label for="example-contact-by-text">Text message</label>
    </div>

  </fieldset>
</div>
```

More info: http://govuk-elements.herokuapp.com/form-elements/

Should we do something similar? Interested to hear both of your thoughts...

**Comment by bengammon** [comment]
That GOV.UK link is out of date. Here's their updated design system: https://design-system.service.gov.uk/components/fieldset/

**Comment by Newnab** [comment]
We're a little inconsistent on the Umbraco side too, but slightly better than the OC BP because we use Umbraco Forms which by default outputs standardised markup, so at least all our projects are v. similar.

I'm fully onboard for basically copying the GovUK principles in terms of markup, although some of their visual choices (e.g using large custom checkboxes) are too opinionated to be a default for my liking.

The semantic, sensible choices they've made do go a long way towards being accessible. I'm not sure it's perfect (maybe need to think more about ARIA) but I think it's a good start.

**Comment by bengammon** [comment]
Ok, cool. I discussed it with @peterkeating earlier today and it seems we're all agreed that in terms of markup, we'll be imitating GOV.UK approach.

In terms of styling, I'll include sensible default styles and then maybe an alternative, but won't take it too far as the style will ultimately be depicted by each individual theme.

**Comment by bengammon** [comment]
Form validation has been removed from the original checklist as a new issue for it has been opened: #82
