### ISSUE TITLE
Improve CSS resets

### ISSUE THREAD

**Issue by bengammon** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#83]
Based on this article that @peterkeating and I were discussing (https://hankchizljaw.com/wrote/a-modern-css-reset/) should we be looking to improve our own reset with any of these techniques?

In particular, the resets using `[class]` and `:not[class]` are particularly interesting.

**Comment by peterkeating** [comment]
Closing this for now as we're sticking with normalize as used by other teams.
