### ISSUE TITLE
Add base ::selection styles

### ISSUE THREAD

**Issue by Newnab** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#84]
[CSS Tricks article on how to approach](https://css-tricks.com/almanac/selectors/s/selection/)

It's an often-overlooked nice touch to have a selection style which is in-keeping with the brand and style of the site. I think a sensible default would be to have the selection background match the `$color-brand-primary` in the theme, set the selection colour to white and remove any text shadow.

**Comment by bengammon** [comment]
I agree that this is a nice touch. Using the brand primary colour is a good idea, presumably added as a theme colour: `color.selection`

Do we think this should be a blanket style to the whole page or applied specifically to text elements?

**Comment by bengammon** [comment]
This has been added to the following pull request: https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/pull/107

**Comment by bengammon** [comment]
This has been approved and merged
