### ISSUE TITLE
Experiment with compressing images

### ISSUE THREAD

**Issue by peterkeating** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#89]
Would be good if the build process could handle compressing images. This would be good if it happened as a pre-commit hook to avoid large images being added to source code repository.

**Comment by JoeBerkley** [comment]
I've seen this done recently in [Roots](https://github.com/roots/sage) where they have a webpack step, which seems like it'd be a good fit for our workflow, if anybody gets a chance to attempt this the roots webpack config for this is [here](https://github.com/roots/sage/blob/master/resources/assets/build/webpack.config.optimize.js)
